### ISSUE TITLE
Very broken

### ISSUE THREAD

**Issue by owlboy** [jackbuehner/google-drive-dark#2]
![screen shot 2019-01-08 at 3 49 14 pm](https://user-images.githubusercontent.com/237349/50860969-fb90ca80-135c-11e9-8341-4bbe1046dae6.png)

**Comment by jackbuehner** [comment]
Looks like some class names were changed - should be fixed in 2541bbfad748083701fcb61a23f887b798514b70

Updating to version 0.1.9 should fix the issue.
https://github.com/jackbuehner/google-drive-dark/raw/master/drive-dark.user.css
